iter5: Добавление библиотеки для парсинга параметров системы
PrEvIeS/url_short pull request #5
Opened 2024-12-08 17:14 UTC by PrEvIeS

2024-12-09 12:44 UTC, s-shpak requested changes
В этом PR должен быть код всего спринта. Для этого сбрось ветвь `main` до первого коммита (`git reset --hard`), после чего запушь изменения (см. `git push -f`). В итоге на этой странице должны появиться изменения все инкрментов.

Кроме того попробуй запустить линтер локально (https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#локальный-запуск) и исправь все подсвеченные ошибки

2024-12-09 12:44 UTC, s-shpak commented on go.mod
Не забывай выполнять `go mod tidy` перед тем как пушить код в репозиторий (для этого можно настроить git-хуки)

2024-12-09 12:44 UTC, s-shpak commented on internal/app/config/config.go
> +		log.Fatal(err)
`log.Fatal` завершает процесс с ненулевым кодом завершения (что указывает на то, что процесс завершился с ошибкой). Не стоит делать это из глубины кода: лучше прокинуть ошибку наверх, т.к. возможно наверху мы сможем ее обработать. Если подходящего обработчика нет, то ошибка должна дойти до точки входа, спровоцировать graceful shutdown приложения и, после, завершение процесса.

2024-12-09 12:44 UTC, s-shpak commented on internal/app/config/config.go
> +	pflag.StringVarP(
Сейчас флаги имеют более высокий приоритет, чем переменные окружения, но в ТЗ есть требование, чтобы было наоборот

2024-12-09 17:54 UTC, PrEvIeS commented on go.mod
Исправил

2024-12-09 17:55 UTC, PrEvIeS commented on internal/app/config/config.go
> +		log.Fatal(err)
Исправил

2024-12-09 17:55 UTC, PrEvIeS commented on internal/app/config/config.go
> +	pflag.StringVarP(
Исправил

2024-12-09 22:57 UTC, s-shpak requested changes
Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2024-12-09 22:57 UTC, s-shpak commented on internal/config/config.go
> +		log.Println(err)
Fallback на дефолтные значения чаще стреляет в ногу, чем помогает. Представь себе, что ты запускаешь сервис с некорректной конфигурацией, и он сразу падает. Ты правишь конфигурацию, далее сервис работает корректно.

Теперь представь, что ты запускаешь сервис, и он запускается, но при инициализации компонентов происходит fallback на дефолтное значение, потому что заданное тобой некорректно. Тогда ты будешь думать, что сервис проиницализирован одним образом, а он будет работать по-другому и неожиданно для тебя.

https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so

2024-12-09 22:57 UTC, s-shpak commented on internal/handler/handler.go
> +		return
Что будет возвращено клиенту при этом ?

2024-12-09 22:57 UTC, s-shpak commented on internal/handler/handler.go
> +		c.String(http.StatusInternalServerError, "Failed to create short URL")
Ошибки которые приводят к статус-коду, который начинается с цифры 4 (400, 401, ...) я называю ошибками 4**. Это штатные ошибки: клиент неправильно обратился к нашему сервису, наш сервис корректно обработал ошибку и вернул ее пользоавтелю. Такие ошибки логировать не надо -- информация о них не дает нам никаких новых данных

С другой стороны ошибки 5** -- те, которые приводят к статус коду, начинающемуся с 5 (500, 501, ...), -- необходимо логировать, т.к. это внутрениие ошибки сервиса, и возникли, потому что сервис столкнулся с неожиданной проблемой. Информацию о них не надо передавать пользователю, т.к. это проблема безопасности

2024-12-09 22:57 UTC, s-shpak commented on internal/handler/handler_test.go
> +		t.Errorf("Expected status %d; got %d", http.StatusCreated, rec.Code)
Вызов `t.Error()` не завершает выполнение тест-кейса, хотя смылса продолжать его, как правило, нет, т.к. после первой ошибки тест обычно более не в валдином состоянии и большинство (если не все) следующие проверки заврешатся с ошибкой. найти при жтиом корневую проблему станет сложнее.

Я бы советовал вызывать `return` после `t.Error()`, чтобы явным образом завершить выполнение тест-кейса.

2024-12-09 22:57 UTC, s-shpak commented on internal/pkg/storage/storage.go
> +	value, exists := s.data[key]
Если функция в Go возвращает вторую переменную булевого типа, которая указывает на корректность выполнения операции и т.п., ее принято называть `ok`.

2024-12-09 22:57 UTC, s-shpak commented on internal/repository/url_repository.go
> +	err := r.storage.Set(shortID, originalURL)
При сокращении URL возможны коллизии: что если сгенерированное значение уже присутствует в хранилище ? Подумай, как решить проблему с коллизиями

2024-12-09 22:57 UTC, s-shpak commented on internal/server/server.go
> +		panic(err)
1. Паниковать не надо: используй `log.Fatal` для:
    1. вывода ошибки
    2. завершения процесса с ошибкой

Прокидывай его максимально наверх (в этом случае до `main`)

2024-12-09 22:57 UTC, s-shpak commented on internal/service/shortener_service.go
> +		log.Printf("Failed to save URL: %v", err)
Ошибки стоит (как правило) логировать в момент, когда они обрабатываются: т.е. когда ошибка возвращена на тот слой, где она может быть обработана, а не прокинута выше.

2024-12-10 08:19 UTC, PrEvIeS commented on internal/config/config.go
> +		log.Println(err)
Поправил

2024-12-10 08:19 UTC, PrEvIeS commented on internal/handler/handler.go
> +		return
Довил тело ответа

2024-12-10 08:19 UTC, PrEvIeS commented on internal/handler/handler.go
> +		c.String(http.StatusInternalServerError, "Failed to create short URL")
Вроде бы понял и поправил

2024-12-10 08:20 UTC, PrEvIeS commented on internal/handler/handler_test.go
> +		t.Errorf("Expected status %d; got %d", http.StatusCreated, rec.Code)
Добавил

2024-12-10 08:20 UTC, PrEvIeS commented on internal/pkg/storage/storage.go
> +	value, exists := s.data[key]
есть

2024-12-10 08:20 UTC, PrEvIeS commented on internal/repository/url_repository.go
> +	err := r.storage.Set(shortID, originalURL)
Добавил решение, которое может решить проблему

2024-12-10 08:20 UTC, PrEvIeS commented on internal/server/server.go
> +		panic(err)
поднял вывод ошибки

2024-12-10 08:21 UTC, PrEvIeS commented on internal/service/shortener_service.go
> +		log.Printf("Failed to save URL: %v", err)
Исправил

2024-12-10 13:21 UTC, s-shpak requested changes

2024-12-10 13:21 UTC, s-shpak commented on internal/config/config.go
> +		log.Fatalf("Error with parsing config: %s", err.Error())
`log.Fatal` завершает процесс с ненулевым кодом завершения (что указывает на то, что процесс завершился с ошибкой). Не стоит делать это из глубины кода: лучше прокинуть ошибку наверх, т.к. возможно наверху мы сможем ее обработать. Если подходящего обработчика нет, то ошибка должна дойти до точки входа, спровоцировать graceful shutdown приложения и, после, завершение процесса.

Graceful shutdown мы будем делать позже, пока досаточно прокинуть ошибку до самого верхнего уровня.

2024-12-10 13:21 UTC, s-shpak commented on internal/handler/handler.go
> +		c.String(http.StatusBadRequest, "Incorrect request")
Для генерации текста ошибки лучше использовать https://pkg.go.dev/net/http#StatusText

2024-12-10 13:21 UTC, s-shpak commented on internal/handler/handler.go
> +		c.String(http.StatusBadRequest, "Failed to create short URL")
Если это Bad request, то ошибку не надо логировать (это ошибка 4**). Но кажется, что это скорее Internal server error

2024-12-10 13:21 UTC, s-shpak commented on internal/handler/handler_test.go
> +		t.Errorf("Expected URL to be stored in storage, but it was not found")
retrun надо добавить везде: я не отмечаю однотипные ошибки, найди в коде все проблемные места

2024-12-10 13:21 UTC, s-shpak commented on internal/repository/url_repository.go
> +	err := r.storage.Set(shortID, originalURL)
Кажется, что стоит попробовать перегенерировать ID (возможно несколько раз). Если это не получилось `n` раз, то можно вернуть клиенту ошибку

2024-12-10 13:21 UTC, s-shpak commented on internal/storage/storage.go
> +type Storage interface {
В Go интерфейсы принято объявлять рядом с местом их использования: в одном пакете и, чаще всего, рядом с функцией/методом, которые их используют. Существуют исключения, но это не тот случай

2024-12-10 13:21 UTC, s-shpak commented on internal/handler/handler_test.go
> +		t.Fatalf("Failed to set URL in storage: %v", err)
Я не советую использовать `t.Fatal()`: в некоторых случаях она может приводить к панике. Лучше использовать `t.Error()` + `return`

2024-12-10 18:58 UTC, PrEvIeS commented on internal/storage/storage.go
> +type Storage interface {
Тут скорее не соглашусь, разделение ответственности мне по идейным соображением мешает использовать коннекторы к хранилищу на одном слое или в одном файле с репозиториями, я бы еще разделил на несколько файлов в модуле storage, чтобы сепарировать реализацию от интерфейса взаимодействия. Например вынести inmemorystorage в отдельный файл, чтобы рядом можно было в случае необходимости добавлять postgres,mysql и прочие адаптеры для доступа к хранилищу данных.

2024-12-10 18:58 UTC, PrEvIeS commented on internal/handler/handler_test.go
> +		t.Fatalf("Failed to set URL in storage: %v", err)
Исправил

2024-12-10 19:01 UTC, PrEvIeS commented on internal/repository/url_repository.go
> +	err := r.storage.Set(shortID, originalURL)
Перегенерация происходит на уровне сервиса, , так как он ответственный за генерацию uid для урла, можно конечно вынести функцию генерации shortId в репозиторий, но на таком маленьком проекте не думаю что это является критическим

2024-12-10 19:03 UTC, PrEvIeS commented on internal/handler/handler_test.go
> +		t.Errorf("Expected URL to be stored in storage, but it was not found")
Исправил

2024-12-10 19:03 UTC, PrEvIeS commented on internal/handler/handler.go
> +		c.String(http.StatusBadRequest, "Failed to create short URL")
Исправил

2024-12-10 19:09 UTC, PrEvIeS commented on internal/handler/handler.go
> +		c.String(http.StatusBadRequest, "Incorrect request")
Переделал

2024-12-10 19:09 UTC, PrEvIeS commented on internal/config/config.go
> +		log.Fatalf("Error with parsing config: %s", err.Error())
Вынес на уровень выше

2024-12-10 20:15 UTC, s-shpak commented on internal/storage/storage.go
> +type Storage interface {
1. Это ты сделаешь позже, в 3-ем спринте
2. Ничто не мешает тебе объявить интерфейс и здесь (для реализации фабрики), и там, где он используется.

Вобщем, это хорошая практика в Go (в других ЯП -- нет), потому перенеси объявление интерфейса туда, где оно используется

2024-12-10 20:17 UTC, s-shpak requested changes

2024-12-10 20:17 UTC, s-shpak commented on internal/service/shortener_service.go
> +		err = s.repo.SaveURL(shortID, originalURL)
Что если проверка завершилась успешно, но до того, как ты добавил новую коротку ссылку в хранилище, другая горутина добавит ее же (случайно сгенерирует такое же значение)? Подумай, как это исправить

2024-12-10 20:17 UTC, s-shpak commented on internal/service/shortener_service.go
> +	for {
Мы рискуем никогда не выйти из этого цикла. Это возможно, если:
1. свободные значения для коротких ссылок уже исчерпаны
2. в логике генерации есть баг

Логичнее было бы попробовать сгенерировать короткую ссылку `n` раз, после чего вернуть ошибку пользователю, если это не получилось

2024-12-15 07:41 UTC, PrEvIeS commented on internal/service/shortener_service.go
> +		err = s.repo.SaveURL(shortID, originalURL)
Поправил

2024-12-16 09:35 UTC, s-shpak requested changes

2024-12-16 09:35 UTC, s-shpak commented on internal/service/shortener_service.go
> +	for range 5 {
Если после 5 попыток не получилось добавить URL в хранилище, мы вернем успешный ответ пользователю, хотя `shortID` будет пустой

2024-12-17 21:52 UTC, s-shpak approved these changes

2024-12-17 22:39 UTC, merged